### ISSUE TITLE
cap deploy gets stuck at [bundler:install] Checking Gemfile and Gemfile.lock changes

### ISSUE THREAD

**Issue by gajendrajena** [ifool/capistrano-faster-rails#1]
just facing this issue from last couple of weeks.

deploy gets stuck at` [bundler:install] Checking Gemfile and Gemfile.lock changes`
Surprisingly bundle install on the release folder works fine.

![image](https://github.com/user-attachments/assets/010ea26d-cc58-47f4-b2cc-e1dde07382a8)

ruby version: 2.7.3
bundler: 2.4.22
rails (6.1.6)

![image](https://github.com/user-attachments/assets/b4b1aea5-632f-493c-b272-832168f1ce72)

`git diff --name-only ... `shows around 50 file changes, but the changes are very minimal.

I had this issue earlier, when I split the commit to smaller chunks, it worked fine. 
But when I squashed and try them in another environment it failed again.

**Comment by ifool** [comment]
fixed
